little bug + correct behaviour when hidden + focus now stays with wanted workspace
tmfink/i3-wk-switch pull request #5
Opened 2019-06-07 14:04 UTC by thirs

1. Corrected a call to i3.command that didn't seem to work.

2. Corrected the behaviour in case want_workspace was hidden on another output. Don't really know what it was doing but it was clearly not as desired (by me, at least).

3. In case we have to swap workspaces, added that the focus should go to want_workspace.

2019-06-09 20:58 UTC, tmfink commented
Thanks for the PR! I'm reviewing it now.

2019-06-09 21:01 UTC, tmfink requested changes

2019-06-09 21:01 UTC, tmfink commented on i3-wk-switch.py
> +
Please trim the trailing whitespace

2019-06-10 19:07 UTC, Synthetica9 approved these changes
Running this on Sway, works very well! Other than the whitespace issue, :+1:

2019-06-11 08:27 UTC, thirs commented on i3-wk-switch.py
> +
Just did.

2019-06-14 08:05 UTC, Synthetica9 commented
@tmfink What is currently holding this up?

2019-06-14 12:33 UTC, merged

2019-06-14 12:33 UTC, tmfink commented
Sorry for the delay--I did not notice commit update.